name: CI to Docker Hub, CD to AWS Elastic Beanstalk

on:
  push:
    branches: [master]

jobs:
  build:
    name: Transpile to JS and Bundle with webpack
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@v2

      - name: Setup Node v10.16.3
        uses: actions/setup-node@v2
        with:
          node-version: "14.17.6"
          cache: "yarn"

      - name: Install depedencies
        run: yarn install

      - shell: bash
        run: |
          npx tsc && yarn webpack && cp package.json build && cp yarn.lock build && cp Dockerfile build

      - name: Upload build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  upload_to_docker_hub:
    name: Build and Upload image to Docker Hub
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./build
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/procon-server:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
