name: CI to Docker Hub, CD to AWS Elastic Beanstalk

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@v2

      - name: Setup Node v14.17.6
        uses: actions/setup-node@v2
        with:
          node-version: "14.17.6"
          cache: "yarn"

      - name: Install depedencies
        run: yarn install

      - name: Transpile and build
        run: yarn tsc:webpack

      - name: Create public directory
        shell: bash
        run: bash ./public.sh

      - name: Generate deployment package
        run: zip -r deploy.zip public

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: server
          environment_name: Server-env
          version_label: 3
          region: us-east-2
          deployment_package: deploy.zip
