name: CI to Docker Hub, CD to AWS Elastic Beanstalk

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@v2

      - name: Setup Node v10.16.3
        uses: actions/setup-node@v2
        with:
          node-version: "10.16"
          cache: "yarn"

      - name: Install depedencies
        run: yarn install

      - name: Transpile and build
        run: npx tsc && yarn webpack

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/procon-server:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
